# Site settings
title: "Thomas Warin CV"
description: "My Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Thomas Warin"
resume_title:                   "Rising Sophomore @ University of Waterloo | Honours Science and Business Co-op"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "twarin@uwaterloo.ca"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+1 (514) 794-3556"
resume_contact_address:         "267 Rachel Est #604, Montreal Canada"

resume_header_contact_info:     "267 Rachel Est #604, Montreal Canada • +1 (514) 794-3556 • twarin@uwaterloo.ca"
display_header_contact_info:    "true"

resume_header_intro: "<p>Hi, I’m Thomas Warin, a rising sophomore in the Honours Science and Business Co-op program at the University of Waterloo and motivated by entrepreneurship focused on applying artificial intelligence and data science to real-world challenges. My interests lie in developing practical AI solutions across a range of sectors, including manufacturing and finance, with a focus on helping organizations improve decision-making, optimize operations, and create measurable value through technology. 

Beyond academics and entrepreneurship, I am actively involved in sports and currently play football for the University of Waterloo. I also have a strong passion for cycling, sailing, and motorsports. My interest in international innovation and technology ecosystems has led me to study Mandarin in Singapore and travel extensively throughout Asia, including China. These experiences have broadened my perspective and reinforced my interest in innovation, entrepreneurship, and cross-cultural collaboration.
</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
#resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
#resume_section_links:           true
resume_section_extracurriculars:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Tamus500"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  #resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/thomas-warin-2063b4243/"
  #resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://qsnxt.ca/"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
