# Site settings
title: "Thomas Warin CV"
description: "My Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Thomas Warin"
resume_title:                   "Rising Sophomore @ University of Waterloo | Honours Science and Business Co-op"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "twarin@uwaterloo.ca"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(514) 794-3556"
resume_contact_address:         "267 Rachel Est, Montreal"

resume_header_contact_info:     "267 Rachel Est, Montreal • (514) 794-3556 • thomas.warin@inoveo.ai"
display_header_contact_info:    "true"

resume_header_intro: "<p>Hi, I’m Thomas Warin, a rising sophomore Honours Science and Business Co-op student at the University of Waterloo and an entrepreneur focused on applying artificial intelligence to real-world business and manufacturing challenges. My academic and extracurricular experiences include developing a medical diagnostic algorithm, leading humanitarian initiatives, and contributing to technology projects in sports and major events. Alongside my technical and entrepreneurial pursuits, I am highly engaged in sports, including Football as I currently play for the University of Waterloo, cycling, sailing, and motorsports. I also have a strong interest in Asia, having studied Mandarin in Singapore and travelled across several countries in the region, including China. My interests center on leveraging emerging technologies to solve practical problems and create meaningful, measurable value.
</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
#resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
#resume_section_links:           true
resume_section_extracurriculars:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Tamus500"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  #resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/thomas-warin-2063b4243/"
  #resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://qsnxt.ca/"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
